class Config:
    DEBUG=False
    UPLOAD_FOLDER = "./media/"
    MAX_CONTENT_LENGTH = 100 * 1000 * 1000
    SECRET_KEY = "23JKH12EŞJKQEQEQW£#>£#£##$>£#>£#£½@QWDEQWJKDQWDQW@WEDKWJHLDJASDWŞAHDAKQŞKDKWD"
